  Style/FrozenStringLiteralComment:
    Enabled: false
  Style/Documentation:
    Enabled: false
  Layout/EmptyLineAfterMagicComment:
    Enabled: false
  Style/FrozenStringLiteralComment:
    Enabled: false
  Metrics/LineLength: 
    Max: 100
  Metrics/ClassLength:
    Enabled: false
  Metrics/MethodLength:
    Max: 20
  Lint/UselessAssignment:
    Enabled: true
  Style/AsciiComments:
    Enabled: false




